version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  default:
    docker:
      - image: circleci/node:14
      - image: circleci/python:2.7

commands:
  npm_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  build:
    executor: default
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "next-with-typescript/package.json" }}

      - run:
          working_directory: next-with-typescript
          name: npm install
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "next-with-typescript/package.json" }}
          paths:
            - next-with-typescript/node_modules

      - run:
          working_directory: next-with-typescript
          name: export
          command: npm run export

      - persist_to_workspace:
          root: next-with-typescript
          paths:
            - out

  deploy_to_stage:
    executor: default
    steps:
      - checkout

      - attach_workspace:
          at: next-with-typescript/out

      - run:
          working_directory: test
          name: test
          command: ls -l

      - aws-s3/sync:
          from: next-with-typescript/out
          to: "s3://staging.nozomikawakami.com"
          overwrite: true

  deploy_to_production:
    executor: default
    working_directory: ~/workspace
    steps:
      - checkout
      - npm_install
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: build
          command: node build/build.js
      - aws-s3/sync:
          from: dist
          to: "s3://nozomikawakami.com"
          overwrite: true

workflows:
  version: 2
  continuous_deploy:
    jobs:
      - build
      - deploy_to_stage:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy_to_production:
          requires:
            - build
          filters:
            branches:
              only: master
