name: GitHub Actions Demo
on: [push]
jobs:
  Deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install NPM packages
        run: npm install
        working-directory: nextjs
      - name: Build app
        run: npm run build
        working-directory: nextjs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: nextjs/out

