name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - master
    types: [closed]

defaults:
  run:
    working-directory: nextjs

jobs:
  Deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: nextjs/out

