name: GitHub Actions Demo
on: [push]

defaults:
  run:
    working-directory: nextjs

jobs:
  Deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install NPM packages
        run: ls
      - name: Build app
        run: ls
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: nextjs/out

